idf_component_register(
    SRCS
        "main.c"
        "chirp_store.c"
        "chirp_prov.c"
        "chirp_sign.c"
        "chirp_send.c"
        "chirp_led.c"
        "wifi_ladder.c"
    INCLUDE_DIRS "."
    PRIV_REQUIRES
        nvs_flash
        json
        esp_wifi
        esp_netif
        esp_event
        esp_timer
        mbedtls
        lwip
        esp_driver_gpio
        esp_driver_tsens
        esp_driver_usb_serial_jtag
)
