#!/usr/bin/env python3
"""Generate sources.mk from ST's CubeIDE .project linked-resource list.
Resolve PARENT-n-PROJECT_LOC paths relative to the CubeIDE project directory."""
import os
import re
import sys

APP = "Projects/NUCLEO-WBA65RI/Applications/Thread/Thread_Cli_Cmd_FTD"
BASE = {"1": APP, "5": "Projects", "6": ""}

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(root)

with open(os.path.join(APP, "STM32CubeIDE", ".project"), encoding="utf-8", errors="replace") as fh:
    proj = fh.read()

csrc, asrc, missing = [], [], []
for m in re.finditer(r"<locationURI>(.*?)</locationURI>", proj, re.S):
    uri = m.group(1).strip()
    mm = re.match(r"PARENT-(\d)-PROJECT_LOC/(.*)", uri)
    if not mm:
        continue
    level, rest = mm.groups()
    prefix = BASE.get(level)
    if prefix is None:
        sys.exit("unhandled PARENT level %s in %s" % (level, uri))
    path = (prefix + "/" + rest) if prefix else rest
    if path.endswith(".c"):
        csrc.append(path)
    elif path.lower().endswith(".s"):
        asrc.append(path)
    else:
        continue
    if not os.path.exists(path):
        missing.append(path)

if missing:
    for p in missing:
        print("MISSING", p, file=sys.stderr)
    sys.exit("%d source file(s) not present - widen the sparse fetch" % len(missing))


def block(name, items):
    if not items:
        return "%s :=\n" % name
    return "%s := \\\n" % name + " \\\n".join("  " + i for i in items) + "\n"


with open("sources.mk", "w", newline="\n") as fh:
    fh.write("# Generated by tools/gen_sources.py - do not edit by hand.\n")
    fh.write("# Source of truth: %s/STM32CubeIDE/.project\n\n" % APP)
    fh.write(block("SRCS", csrc))
    fh.write("\n")
    fh.write(block("ASRCS_PROJ", asrc))

print("sources.mk: %d C, %d ASM, 0 missing" % (len(csrc), len(asrc)))
